version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.phlab.software'
        letsencrypt['enable'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = false
        nginx['real_ip_trusted_addresses'] = ['127.0.0.1', 'localhost']
        nginx['real_ip_header'] = 'X-Forwarded-For'
        nginx['real_ip_recursive'] = 'on'
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - gitlab_network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 16G
          cpus: "4"
      restart_policy:
        condition: on-failure

networks:
  gitlab_network:
    external: true
    name: web_network

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
