version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/cache:/var/cache/nginx
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - web_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  web_network:
    external: true
    name: web_network
